---
title: "Course Guidelines"
editor: visual
execute:
  echo: true
---

## Step 1: Get R

In order to run swirl, you must have R 3.1.0 or later installed on your computer. If you are on a Linux operating system, please visit our [Installing swirl on Linux](https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux) page.

If you need to install R, you can do so [here](http://cran.rstudio.com/).

For help installing R, check out one of the following videos (courtesy of Roger Peng at Johns Hopkins Biostatistics):

[Installing R on Windows](http://youtu.be/mfGFv-iB724) [Installing R on Mac](http://youtu.be/Icawuhf0Yqo)

## Step 2 (optional): Get RStudio

In addition to R, it’s recommended that you install RStudio, which will make your experience with R much more enjoyable.

If you need to install RStudio, you can do so [here](http://www.rstudio.com/products/rstudio/download/). Select the appropriate installer for your operating system.

## Step 3: Install swirl

**You only need to do this once.**

Open RStudio (or just plain R if you don't have RStudio) and type the following into the console:

`> install.packages("swirl")`

Note that the `>` symbol at the beginning of the line is R's prompt for you type something into the console. We include it here so you know that this command is to be typed into the console and not elsewhere. The part you type begins after `>`.
