---
title: "Course Home"
format: html
editor: visual
---

## STS_ST07_Programming_in R

Welcome to the course website for "Programmation en R" (STS_ST07_Programming_in R).

Please read the [course guidelines](installation_guidelines.qmd).

The best environment to learn the R programming language, is R. Therefore, this course is organized as an **R programming workshop**. From the first session on, we will engage in executing specific tasks in R, while learning new parts of the R programming language every week. We will use a program called `swirl` to provide immediate assessment and helpful feedback in R as you work through the lessons.

Each session will alternate between:

1.  A few **swirl lessons** of *15–20 minutes*\
2.  A **summary** of the most important newly acquired aspects, including some extra information and best-practice guidelines\
3.  An **assignment** that repeats much of the lesson material, but with new data and without the feedback from `swirl`

Please, make sure that you have, before the the start of our first session, R installed on your computer.

You will find some guidelines for the installation of R [here](installation_guidelines.qmd). You can work directly in the R console or in RStudio. But in order to run swirl, you must have R 3.1.0 or later installed.

## Requirements for EDSTS Credit Validation

To earn credit for this course, you must meet **all** of the following requirements:

1.  **Attend all sessions on Zoom**
    -   You must be logged into the Zoom meeting for the **entire duration** of each session (unless you have a valid justification).
    -   You must sign in using your **real name**, with your **full last name spelled out**.
    -   If you are unable to attend a session, you must provide a **justification** to both the instructor and the doctoral school.
2.  **Complete all required *swirl* lessons**
    -   All `swirl` lessons listed below must be completed **by Friday, January 31 at 6:00 PM**.

## The order of the swirl lessons and assignments to be completed is the following

1.  Basic Building Blocks\
2.  <span style="color:red;">Exercise 1\
3.  Workspace, Directories, and Files\
4.  <span style="color:red;">Exercise 2\
5.  Data Classes\
6.  Logic\
7.  Sequences of Numbers\
8.  Subsetting Vectors\
9.  Matrices and Data Frames\
10. <span style="color:red;">Exercise 3\
11. <span style="color:red;">Exercise 4\
12. Lists\
13. Lists: Examples\
14. lapply() and sapply()\
15. vapply() and tapply()\
16. Functions\
17. <span style="color:red;">Exercise 5\
18. <span style="color:red;">Exercise 6

Extra exercises can be provided on demand.
